### PR TITLE
Feature: Proposal of branching system

### PR DESCRIPTION
**Pull request by Plep-m**
Hello there,
I played around your library in my project and it is truly a blast to use but a branching system was a bit lacking so here is my first proposal.
Here is what i added : 
 - a new syntax with new [branch] , [target:] , (end) tag 
 - a way to opt in or out fading 
 - and a way to config the dialogbox 
 
 line number of target might be confusing at first but i think it's not too bad, a line will be counted a line is it start with a character name, so you just have to count them to know where to redirect your target
 also some improbement would probably be needed cause currently you cant disaply both text and choice at the same time

### CODE REVIEW

**Comment by Rena-afk-c** [comment]
I really like the changes actually, but i have a question, are these compatible with my current implementations? Since i work in origin-dev branch and i already started implementing tag effects,Can you verify with other branch. If you check and see, my current new implementation includes wavy text , wait and shake tags

**Comment by Rena-afk-c** [comment]
I just merged my dev branch into main, there are couple of conflicts, as i made changes in the system.  Following is the example of the new changes i worked on . 
image
image

**Comment by Plep-m** [comment]
Sure things I will check on your other branch tomorrow and I'll resolve the conflicts

**Comment by Plep-m** [comment]
Everything should work as they should now i merged both our feature and prepared a nice exemple file

**Comment by Rena-afk-c** [comment]
Looks
Good to me! I'll merge in a bit :) thanks for the contribution:))

**Comment by Plep-m** [comment]
You are welcome I'll probably make some more contribution if I need anything else since I'll be actively using this in my project :) 
Feel free to open any issues I'll look at it

**Comment by Rena-afk-c** [comment]
Merged!

**Pull request merged**
